Contact form branch Project
3nityGitHub/Portfolio-setup pull request #3
Opened 2022-10-05 16:23 UTC by 3nityGitHub

#In this PR,

- I created a new branch (Contact_form_branch)
- I added a new section/container for the contact form page
- I added the HTML form tags
- I styled the HTML form tags with CSS

2022-10-05 19:07 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @3nityGitHub , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

- [ ] Kindly make sure the body takes a max screen so that it will remove the scrolling button from left to right as shown in the picture below. you can make that by giving the  body of your project the max of 100% :+1: 

![image](https://user-images.githubusercontent.com/95297251/194138989-24982854-b2d0-479e-91c4-b3d3dafd6936.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-10-05 19:07 UTC, MaganaAsiati commented on index.html
>        <section class="footer_section">
Kindly makes sure your icon design stick as much as possible to the Figma design provided as is shown in the picture below the color is not the same. To fix that I can suggest you use this  `color: #505F79` is the one used in the Figma design :+1: 

## You design 

![image](https://user-images.githubusercontent.com/95297251/194140177-53a71aff-afaa-408a-96e8-0ee5af221457.png)

## Figma design 

![image](https://user-images.githubusercontent.com/95297251/194141866-4d48f15d-f216-42d4-8282-03f101fee100.png)

2022-10-05 23:07 UTC, 3nityGitHub commented on styles.css
> +  height: 500px;
@MaganaAsiati Thanks for the wonderful review and required changes. For this request, i honestly don't understand what you are talking about. Can you be more specific as to the changes you want me to make.
Thanks.

2022-10-06 00:37 UTC, Qoosim approved these changes
#  # *Status: Approved* :tada: :heavy_check_mark: 

Hi @3nityGitHub and @EngruugbeJimmy, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_**Kindly check some optional comments I left under the review**_ :pray: 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 

![](https://camo.githubusercontent.com/9ab1354ab399a31c604186cd2e7c09a0d4704215a1eda3e29a02fc52bf3f6bf5/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6d474b31673838485a526132466c4b47627a2f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [OPTIONAL] It is required for name input to have `maxlength="30"` not `maxlength="50"`. kindly change it.
- [OPTIONAL] As suggested by the previous reviewer. There's horizontal scroll bar on your page which is currently rendering your page with some faults. Take a look at some screenshots below and fix that.

![hor-line-1](https://user-images.githubusercontent.com/26597432/194187928-94a5e882-d5ca-4dc6-ba82-3ba4a17ba1d0.png)


![hor-line-2](https://user-images.githubusercontent.com/26597432/194187948-7b4c5e19-4405-44dc-bd08-583641405ffb.png)


![hor-line-3](https://user-images.githubusercontent.com/26597432/194187966-7beaf852-caf0-4678-abc5-645a18fab52c.png)


[OPTIONAL] This is stated optional, but highly recommended to fix it. One of the footer icons is now showing properly. Kindly look into that too and fix it.

![your-footer-icon](https://user-images.githubusercontent.com/26597432/194188088-30125f66-13cb-4fe6-af20-adf86e8d4e5f.png)

2022-10-06 14:07 UTC, merged